# Generated by Django 5.2.3 on 2025-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Company Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Company Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Company Address')),
                ('city', models.CharField(max_length=255, verbose_name='Company City')),
                ('country', models.CharField(max_length=255, verbose_name='Company Country')),
                ('website', models.CharField(max_length=255, verbose_name='Company Website')),
                ('industry', models.CharField(max_length=255, verbose_name='Company Industry')),
                ('employee_count', models.CharField(max_length=255, verbose_name='Company Employee Count')),
                ('description', models.TextField(verbose_name='Company Description')),
                ('logo', models.ImageField(upload_to='media/', verbose_name='Company Logo')),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
