# Generated by Django 5.1.4 on 2025-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company City'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Country'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Company Description'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='employee_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Employee Count'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Industry'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Company Website'),
        ),
    ]
